source 'https://rubygems.org'

gem 'rake', '~> 10.3.2'
gem 'mysql2', '~> 0.3.17'

gem 'rspec', '~> 3.1.0'
gem 'rspec-rails', '~> 3.1.0'

# Load DbCharmer as a gem
if ENV['DB_CHARMER_GEM'].to_s == ''
  gem_path = File.expand_path(File.dirname(File.dirname(__FILE__)))
  puts "Using on-disk db-charmer code from '#{gem_path}'..."
  gem 'db-charmer', path: gem_path
else
  puts "Using db-charmer gem: #{ENV['DB_CHARMER_GEM']}..."
  gem 'db-charmer', ENV['DB_CHARMER_GEM']
end

# Detect Rails version we need to use
rails_version_file = File.expand_path("../.rails-version", __FILE__)
version = File.exist?(rails_version_file) && File.read(rails_version_file).chomp
version ||= ENV['RAILS_VERSION']
version ||= '3-2-stable'

# Require gems for selected rails version
case version
when /master/
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'journey', github: 'rails/journey'
when /3-2-stable/
  gem 'rails', github: 'rails/rails', branch: '3-2-stable'
else
  gem 'rails', version
end
